export {
  initSubstitutionPage,
  updatePageForContext,
  loadSubstitutionByDate,
  validateSubstitutionAccess,
  switchToHallOfFame,
  switchToSubstitutionSchedule,
  switchToSubstitutionManagement,
  exportSubstitutionData,
  exportMonthlySubstitutionReport,
  renderHallOfFame,
  renderSubstitutionExportBar,
  renderSubstituteRanking,
  renderSubstituteStats,
  renderDatePicker,
  renderAbsentTeacherCards,
  renderSubstituteAssignments,
  renderSubstitutionManagement,
  calculateSubstituteStats,
  generateSubstituteRanking
} from './core.js';
